/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AccountRole;

import Business.WorkQueue.PatientDetailsRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author Nauka Salot
 */
public class Payment extends javax.swing.JPanel {

    /**
     * Creates new form Payment
     */
    private JPanel userProcessContainer;
    private PatientDetailsRequest pdr;

    Payment(JPanel userProcessContainer, PatientDetailsRequest pdr) {
        //To change body of generated methods, choose Tools | Templates.
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.pdr = pdr;
        populate();
    }

    public void populate() {
        //Instant start = Start.getDate().toInstance();
        //int days=Days.daysBetween();
        ZonedDateTime start = pdr.getPatientDetails().getRoomDetails().getAdate().toInstant().atZone(ZoneId.systemDefault());
        ZonedDateTime end = pdr.getPatientDetails().getRoomDetails().getDdate().toInstant().atZone(ZoneId.systemDefault());
        //Duration duration = Duration.between(start, end);   
        int diff = end.getDayOfMonth() - start.getDayOfMonth();
        txtdays.setText(String.valueOf(diff));
        double charges = pdr.getPatientDetails().getRoomDetails().getPrice() * diff;
        txtcharges.setText(String.valueOf(charges));
        double servicecharges = (int) charges * 0.2;
        txtservice.setText(String.valueOf(servicecharges));
        double totalcharges = charges + servicecharges;
        double coverage = pdr.getPatientDetails().getInsurance().getCoverage();
        double payable = totalcharges - coverage;
        if (payable < 0) {
            txtpayableamt.setText("All charges covered in insurance");
        } else {
            txtpayableamt.setText(String.valueOf(payable));
        }
        txttotalcharges.setText(String.valueOf(totalcharges));
        txtinsurancetype.setText(pdr.getPatientDetails().getInsurance().getInsuranceType());
        txtcoverage.setText(String.valueOf(coverage));

        SimpleDateFormat sdf = new SimpleDateFormat("dd/M/yyyy");
        String date = sdf.format(new Date());
        //System.out.println(date);
        txtbillingdate.setText(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtdays = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtcharges = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtservice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtbillingdate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txttotalcharges = new javax.swing.JTextField();
        txtinsurancetype = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtcoverage = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtpayableamt = new javax.swing.JTextField();
        btnback = new javax.swing.JButton();

        jLabel1.setFont(btnback.getFont());
        jLabel1.setText("PAYMENT");

        jLabel2.setFont(btnback.getFont());
        jLabel2.setText("Number of Days");

        txtdays.setPreferredSize(new java.awt.Dimension(60, 30));

        jLabel3.setFont(btnback.getFont());
        jLabel3.setText("Total Room Charges");

        txtcharges.setPreferredSize(new java.awt.Dimension(60, 30));

        jLabel4.setFont(btnback.getFont());
        jLabel4.setText("Service Charges");

        txtservice.setPreferredSize(new java.awt.Dimension(60, 30));
        txtservice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtserviceActionPerformed(evt);
            }
        });

        jLabel5.setFont(btnback.getFont());
        jLabel5.setText("Billing Date");

        txtbillingdate.setPreferredSize(new java.awt.Dimension(60, 30));

        jLabel6.setFont(btnback.getFont());
        jLabel6.setText("Total Charges");

        jLabel7.setFont(btnback.getFont());
        jLabel7.setText("Insurance Type");

        txttotalcharges.setPreferredSize(new java.awt.Dimension(60, 30));

        txtinsurancetype.setPreferredSize(new java.awt.Dimension(60, 30));

        jLabel8.setFont(btnback.getFont());
        jLabel8.setText("Coverage");

        txtcoverage.setPreferredSize(new java.awt.Dimension(60, 30));

        jLabel9.setFont(btnback.getFont());
        jLabel9.setText("Payable Amount");

        txtpayableamt.setPreferredSize(new java.awt.Dimension(60, 30));

        btnback.setFont(new java.awt.Font("Khmer UI", 1, 14)); // NOI18N
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/DoctorRole/1449546840_restart-1.png"))); // NOI18N
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnback)
                        .addGap(153, 153, 153)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtservice, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(txtcharges, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txttotalcharges, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtbillingdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtinsurancetype, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtdays, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtcoverage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtpayableamt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnback))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtdays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcharges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtservice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtbillingdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txttotalcharges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtinsurancetype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtcoverage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtpayableamt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtserviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtserviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtserviceActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtbillingdate;
    private javax.swing.JTextField txtcharges;
    private javax.swing.JTextField txtcoverage;
    private javax.swing.JTextField txtdays;
    private javax.swing.JTextField txtinsurancetype;
    private javax.swing.JTextField txtpayableamt;
    private javax.swing.JTextField txtservice;
    private javax.swing.JTextField txttotalcharges;
    // End of variables declaration//GEN-END:variables
}
