/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ReceptionistRole;

import Business.Employee.Employee;
import Business.RoomDetails.RoomDetails;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Nauka Salot
 */
public class AssignRoom extends javax.swing.JPanel {

    private RoomDetails roomDetails;
    private JPanel userProcessConatiner;
    private Employee employee;
    private Date admitDate;
    private Date dischargeDate;

    /**
     * Creates new form AssignRoom
     */

    AssignRoom(JPanel userProcessContainer, Employee employee) {
        initComponents();
         //To change body of generated methods, choose Tools | Templates.

        this.userProcessConatiner = userProcessContainer;
        this.employee = employee;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtroomno = new javax.swing.JTextField();
        txtdoctorname = new javax.swing.JTextField();
        txtsubmit = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dcadmit = new com.toedter.calendar.JDateChooser();
        dcdischarge = new com.toedter.calendar.JDateChooser();
        btnback = new javax.swing.JButton();

        jLabel1.setText("Assign Room");

        jLabel3.setText("Room No:");

        jLabel4.setText("Doctor Name:");

        jLabel5.setText("Room Type:");

        txtdoctorname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdoctornameActionPerformed(evt);
            }
        });

        txtsubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/DoctorRole/1449545183_floppy.png"))); // NOI18N
        txtsubmit.setText("Submit");
        txtsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubmitActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---Select Category---", "Delux", "Super Delux", "Family", "Special" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Price:");

        txtprice.setEditable(false);
        txtprice.setEnabled(false);

        jLabel8.setText("Admit Date");

        jLabel9.setText("Discharge Date:");

        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/DoctorRole/1449546840_restart-1.png"))); // NOI18N
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtsubmit)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnback)
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(40, 40, 40)
                                .addComponent(txtdoctorname))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(59, 59, 59)
                                .addComponent(txtroomno))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(53, 53, 53)
                                .addComponent(dcadmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(29, 29, 29)
                                .addComponent(dcdischarge, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(btnback))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dcdischarge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(dcadmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtroomno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtdoctorname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)))
                .addGap(27, 27, 27)
                .addComponent(txtsubmit)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents
//SimpleDateFormat sdf = new SimpleDateFormat("ddMMyyyy");
// Calendar cal1 = new GregorianCalendar();
//     Calendar cal2 = new GregorianCalendar();
//     //Date date = sdf.parse("your first date");
//     cal1.setTime(Date);
//     date = sdf.parse("your second date");
//     cal2.setTime(date);
    private void txtdoctornameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdoctornameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdoctornameActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        //int price;
        String opt = String.valueOf(jComboBox1.getSelectedItem());

        switch (opt) {
            case "Delux":
                txtprice.setText("1200");
                break;
            case "Super Delux":
                txtprice.setText("2000");
                break;
            case "Family":
                txtprice.setText("3000");
                break;
            case "Special":
                txtprice.setText("5000");
                break;

        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubmitActionPerformed
        // TODO add your handling code here:
//        Date date = dcadmit.getDate();
//        String strDate = DateFormat.getDateInstance().format(date);
//        dcadmit.setDate(date);
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        int p = Integer.parseInt(txtprice.getText());
//String date = sdf.format(JDateChooser.getSelectedDate().getTime());
//jLabel1.setText(date);
        roomDetails = new RoomDetails();
        roomDetails.setAdate(dcadmit.getDate());
        roomDetails.setDdate(dcdischarge.getDate());

       // roomDetails.setAdmitDate(txtadmitdate.getText());
        // roomDetails.setDischargeDate(txtdischargedate.getText());
        roomDetails.setDoctorName(txtdoctorname.getText());
        roomDetails.setRoomNo(Integer.parseInt(txtroomno.getText()));
        roomDetails.setRoomType((String) jComboBox1.getSelectedItem());
        roomDetails.setPrice(p);
        roomDetails.setEmployee(employee);
        employee.getPdr().getPatientDetails().setRoomDetails(roomDetails);
        JOptionPane.showMessageDialog(null, "Added Successfully");


    }//GEN-LAST:event_txtsubmitActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        userProcessConatiner.remove(this);
        CardLayout layout = (CardLayout) userProcessConatiner.getLayout();
        layout.previous(userProcessConatiner);
    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private com.toedter.calendar.JDateChooser dcadmit;
    private com.toedter.calendar.JDateChooser dcdischarge;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtdoctorname;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtroomno;
    private javax.swing.JButton txtsubmit;
    // End of variables declaration//GEN-END:variables
}
