/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HomePersonRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.AmbulanceOrganization;
import Business.Organization.Organization;
import Business.Organization.PersonOrganization;
import Business.PersonVitalSigns.PersonVitalSignHistory;
import Business.PersonVitalSigns.PersonVitalSigns;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AmbulanceWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Nauka Salot
 */
public class HomePersonWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HomePersonWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private PersonOrganization organization;
    private EcoSystem business;
    private UserAccount account;
    private PersonVitalSigns personVitalSign;
    private PersonVitalSignHistory personVitalSignHistory;
    private Enterprise enterprise;

    public HomePersonWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, PersonOrganization personOrganization, Enterprise enterprise, EcoSystem business) {
        //To change body of generated methods, choose Tools | Templates.
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = personOrganization;
        this.business = business;
        this.enterprise = enterprise;
        this.account = account;
        txtsubmit.setEnabled(false);
        Employee emp = account.getEmployee();
        personVitalSignHistory = emp.getPersonVitalSignHistory();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtrespiratoryrate = new javax.swing.JTextField();
        txtheartrate = new javax.swing.JTextField();
        txtbloodpressure = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        txtgenerate = new javax.swing.JButton();
        txtsubmit = new javax.swing.JButton();
        btnview = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel1.setText("Respiratory Rate");

        jLabel2.setText("Heart Rate");

        jLabel3.setText("Blood Pressure");

        jLabel4.setText("Age");

        txtgenerate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/HomePersonRole/1449547987_add-to-favorites.png"))); // NOI18N
        txtgenerate.setText("Generate Vital Signs");
        txtgenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgenerateActionPerformed(evt);
            }
        });

        txtsubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/DoctorRole/1449545183_floppy.png"))); // NOI18N
        txtsubmit.setText("Submit");
        txtsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubmitActionPerformed(evt);
            }
        });

        btnview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/HomePersonRole/1449548055_Glasses.png"))); // NOI18N
        btnview.setText("View");
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtsubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnview)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(txtrespiratoryrate, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtheartrate, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtbloodpressure, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(txtage)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(txtgenerate)))
                .addGap(20, 122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtgenerate)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtrespiratoryrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtheartrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtbloodpressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsubmit)
                    .addComponent(btnview))
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtgenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgenerateActionPerformed
        // TODO add your handling code here:
        //PersonVitalSigns pvs=new PersonVitalSigns();
        //pvs.setBloodpressure();

        personVitalSign = personVitalSignHistory.addvitalsign();

        int bp = (int) (Math.random() * 100);
        int hr = (int) (Math.random() * 100);
        int rr = (int) (Math.random() * 100);
        int age = (int) (Math.random() * 100);
        txtbloodpressure.setText(String.valueOf(bp));
        txtheartrate.setText(String.valueOf(hr));
        txtrespiratoryrate.setText(String.valueOf(rr));
        txtage.setText(String.valueOf(age));

        personVitalSign.setBloodpressure(bp);
        personVitalSign.setHeartrate(hr);
        personVitalSign.setAge(age);
        personVitalSign.setRespiratoryrate(rr);

        txtsubmit.setEnabled(true);

    }//GEN-LAST:event_txtgenerateActionPerformed

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
        // TODO add your handling code here:
        View v = new View(userProcessContainer, personVitalSignHistory);
        userProcessContainer.add("View", v);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnviewActionPerformed

    private void txtsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubmitActionPerformed
        // TODO add your handling code here:
//        if(txtheartrate.getText()==null || txtbloodpressure.getText()==null || txtrespiratoryrate.getText()==null || txtage.getText()==null)
//        {
//        
//        }
        int age = Integer.parseInt(txtage.getText());
        int rr = Integer.parseInt(txtrespiratoryrate.getText());
        int hr = Integer.parseInt(txtheartrate.getText());
        int bp = Integer.parseInt(txtbloodpressure.getText());
        if ((age >= 1 && age <= 3) && (rr >= 20 && rr <= 30) && (hr >= 80 && hr <= 130) && (bp >= 80 && bp <= 110)) {
        } else {
            AmbulanceWorkRequest request = new AmbulanceWorkRequest();
        //UserAccount ua=(UserAccount) tbldoctor.getValueAt(selectedRowNurse, 0);
            //Employee e=(Employee) tblpatient.getValueAt(selectedRow, 0);
            //request.setMessage(message);
            request.setSender(account);
            //request.set(e);
            request.setStatus("Sent");

        //request.setReceiver(ua);
            Organization org = null;
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof AmbulanceOrganization) {
                    org = organization;
                    break;
                }
            }
            if (org != null) {
            // org.getUserAccountDirectory().getUserAccountList().add(ua);
                //userAccount.getWorkQueue().getWorkRequestList().add(request);

                org.getWorkQueue().getWorkRequestList().add(request);
                JOptionPane.showMessageDialog(null, "Sent to Ambulance");
            }
            
            txtgenerate.setEnabled(false);

        }
    }//GEN-LAST:event_txtsubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnview;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtbloodpressure;
    private javax.swing.JButton txtgenerate;
    private javax.swing.JTextField txtheartrate;
    private javax.swing.JTextField txtrespiratoryrate;
    private javax.swing.JButton txtsubmit;
    // End of variables declaration//GEN-END:variables
}
